### ISSUE TITLE
Big question upload

### ISSUE THREAD

**Issue by ghost** [amagliul/odrive-utilities#4]
Sorry for this question
anybody know how i upload ,sync archives locally to cloud

i sync folders and archives from the cloud to my pc but i cant upload news to cloud
i add Deep-house-relax.tar archive to folder

i use that but doesn fuction
"$HOME/.odrive-agent/bin/odrive" backup "$HOME/odrive-agent-mount/Drivepro/Shared/MUSICA/Deep-house-relax.tar"
Unable to sync Deep-house-relax.tar.  Please use a placeholder path.

python "$HOME/.odrive-agent/bin/odrive.py" sync "$HOME/odrive-agent-mount/Drivepro/Shared/MUSICA/Deep-house-relax.tar" 
Unable to sync Deep-house-relax.tar.  Please use a placeholder path.

maybe i need to change to pCloud

**Comment by amagliul** [comment]
Hi @abdiasriver. 
Uploads are automatic, but you may need to issue a `refresh` command on the folder path containing the file to have it picked-up right away. Without the refresh it should eventually get to it, though.

If you are still having issues, the odrive forum is the best place to go: forum.odrive.com
