### ISSUE TITLE
error: argument placeholderPath: invalid unicode_path value

### ISSUE THREAD

**Issue by iptvcld** [amagliul/odrive-utilities#5]
Hello; Hoping someone is able to assist; i am running a CLI sync and I am getting the below error output

error: argument placeholderPath: invalid unicode_path value
Tim\xe2\x80\x99s iPhone.cloudf

I noticed that the comma is not the standard - does not look like it is handling UTF-8, any suggestions? I have a bunch of folder that are showing this way 

I am using this
exec 6>&1;output="go"; while [ "$output" ]; do output=$(find "$HOME/odrive-agent-mount/Dropbox/" -name "*.cloud*" -exec python "$HOME/.odrive-agent/bin/odrive.py" sync "{}" \;|tee /dev/fd/6); done

Thank you

**Comment by amagliul** [comment]
Sorry I missed this here, but I'm glad we were able to work it out on the odrive forum.
