### ISSUE TITLE
How do I sign into the iOS application?

### ISSUE THREAD

**Issue by DavidBlowi** [amagliul/odrive-utilities#7]
It asks for an "ODRIVE ID". But I have never heard of any ID.

**Comment by amagliul** [comment]
Hi @DavidBlowi,
My apologies for not seeing this earlier. We don't have an available iOS app. We did have one for a beta product that was discontinued a while ago. The app isn't available on the app store, so maybe this was something that you installed a long time ago?

**Comment by DavidBlowi** [comment]
@amagliul Thanks for the reply! 

Yes I did install it quite a long time ago. 

I enjoyed it so much. Is there any way to use your service on my iPhone 12 Pro? Do you have an app in the beta stage on TestFlight maybe?
